---
version: "3.8"
services:
  #postgres db
  db:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pg16
    networks:
      - backbone
    ports:
      - 5432:5432/tcp

  #postgres ui
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=YES
    networks:
      - backbone
    ports:
      - 5050:80/tcp

  #redis
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    environment:
      #- REDIS_PASSWORD=
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    networks:
      - backbone
    ports:
      - 6379:6379/tcp
      - 8001:8001/tcp
    #command: --requirepass ""
    volumes:
      - ./data/redis:/data

  #elastic Not implemented yet
  
 


networks:
  backbone:
    driver: bridge